# Generated by Django 5.0.6 on 2024-07-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
